[build-system]
requires = ["scikit-build-core", "pybind11", "setuptools"]
build-backend = "scikit_build_core.build"

[project]
name = "proxi"
version = "0.1.0"
description = "Proxi: Accelerating nearest-neighbor search for high-dimensional data!"
authors = [
    { name = "Siddhant Biradar" }
]
requires-python = ">=3.8"
readme = "README.md"
license = {text = "Apache 2.0"}

[tool.scikit-build]
cmake.minimum-version = "3.15"
wheel.packages = ["proxi"]
