# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install build tools
        run: python -m pip install --upgrade pip build auditwheel

      - name: Build and Prepare Distributions
        run: |
          # Create fresh directories
          rm -rf dist wheelhouse
          mkdir -p dist wheelhouse

          # Build sdist and wheel into wheelhouse
          python -m build --sdist --wheel --outdir wheelhouse/

          # Copy sdist to dist
          cp wheelhouse/*.tar.gz dist/

          # Repair Linux wheel(s) if any, and place them in dist/
          # Assumes package name is 'proxiss' for the wheel filename glob
          FOUND_LINUX_WHEEL=0
          for f_whl in wheelhouse/proxiss-*-linux_*.whl; do
            if [ -e "$f_whl" ]; then # Check if glob matched a file
              echo "Repairing Linux wheel: $f_whl"
              auditwheel repair "$f_whl" --plat manylinux2014_x86_64 -w dist/
              FOUND_LINUX_WHEEL=1
            fi
          done

          # If no Linux-specific wheel was found/repaired, check for pure Python wheels
          if [ "$FOUND_LINUX_WHEEL" -eq 0 ]; then
            for f_whl in wheelhouse/proxiss-*-py3-none-any.whl; do
              if [ -e "$f_whl" ]; then
                echo "Copying pure Python wheel: $f_whl"
                cp "$f_whl" dist/
              fi
            done
          fi

          # Clean up temporary directory
          rm -rf wheelhouse/

          echo "Final contents of dist/:"
          ls -l dist/

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    # For more information, see: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#deployment-protection-rules
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT
      #
      # ALTERNATIVE: if your GitHub Release name is the PyPI project version string
      # ALTERNATIVE: exactly, uncomment the following line instead:
      # url: https://pypi.org/project/YOURPROJECT/${{ github.event.release.name }}

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
